### ISSUE TITLE
Bug : Docker Compose Image & GitHub Token

### ISSUE THREAD

**Issue by nikkhilmali** [heroyooki/ocpp-garage#4]
In docker compose file the image for "ocpp-gateway" is not publicly available. 

IMAGE : "heroyooki/charge_point_node:${IMAGE_TAG}"

And for docker file from where we are going to get GITHUB TOKEN

**Comment by AdrielGraminho** [comment]
yes, this is making it difficult for me to take my first test

**Comment by heroyooki** [comment]
This is not a bug.  Those have restricted and managed access. Unapproved.

**Comment by nikkhilmali** [comment]
So, how i can get this project running?

**Comment by heroyooki** [comment]
Actually, the project runs only for customers. The repository is just a generally described approach proved by the code.
